
package com.traveliko.platform.ws.rategain;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Reservation", targetNamespace = "http://cgbridge.rategain.com/2011A")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Reservation {


    /**
     * 
     * @param otaHotelResNotifRQ
     * @return
     *     returns com.traveliko.platform.ws.rategain.OTAHotelResNotifRS
     */
    @WebMethod(operationName = "OTA_HotelResNotifRQ", action = "http://cgbridge.rategain.com/2011A/ReservationService/HotelResNotif")
    @WebResult(name = "OTA_HotelResNotifRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05", partName = "OTA_HotelResNotifRS")
    public OTAHotelResNotifRS otaHotelResNotifRQ(
        @WebParam(name = "OTA_HotelResNotifRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05", partName = "OTA_HotelResNotifRQ")
        OTAHotelResNotifRQ otaHotelResNotifRQ);

}
