
package com.traveliko.platform.ws.rategain;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.0.13
 * 2017-07-26T12:04:46.862+05:00
 * Generated source version: 3.0.13
 * 
 */
public final class Reservation_ReservationServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://cgbridge.rategain.com/2011A", "ReservationService");

    private Reservation_ReservationServiceSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ReservationService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ReservationService ss = new ReservationService(wsdlURL, SERVICE_NAME);
        Reservation port = ss.getReservationServiceSoap();  
        
        {
        System.out.println("Invoking otaHotelResNotifRQ...");
        com.traveliko.platform.ws.rategain.OTAHotelResNotifRQ _otaHotelResNotifRQ_otaHotelResNotifRQ = null;
        com.traveliko.platform.ws.rategain.OTAHotelResNotifRS _otaHotelResNotifRQ__return = port.otaHotelResNotifRQ(_otaHotelResNotifRQ_otaHotelResNotifRQ);
        System.out.println("otaHotelResNotifRQ.result=" + _otaHotelResNotifRQ__return);


        }

        System.exit(0);
    }

}
