package com.traveliko.platform.ws.rategain;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.13
 * 2017-07-26T12:04:46.942+05:00
 * Generated source version: 3.0.13
 * 
 */
@WebServiceClient(name = "ReservationService", 
                  wsdlLocation = "file:DirectConnectReservation.wsdl",
                  targetNamespace = "http://cgbridge.rategain.com/2011A") 
public class ReservationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cgbridge.rategain.com/2011A", "ReservationService");
    public final static QName ReservationServiceSoap = new QName("http://cgbridge.rategain.com/2011A", "ReservationServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:DirectConnectReservation.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ReservationService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:DirectConnectReservation.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ReservationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ReservationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReservationService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ReservationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ReservationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ReservationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns Reservation
     */
    @WebEndpoint(name = "ReservationServiceSoap")
    public Reservation getReservationServiceSoap() {
        return super.getPort(ReservationServiceSoap, Reservation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Reservation
     */
    @WebEndpoint(name = "ReservationServiceSoap")
    public Reservation getReservationServiceSoap(WebServiceFeature... features) {
        return super.getPort(ReservationServiceSoap, Reservation.class, features);
    }

}
