
package com.traveliko.ws.platform.rategain;

import javax.jws.WebService;
import javax.xml.ws.BindingType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(portName = "ReservationServiceSoap", serviceName = "ReservationService", targetNamespace = "http://cgbridge.rategain.com/2011A", wsdlLocation = "/DirectConnectReservation.wsdl", endpointInterface = "com.traveliko.ws.platform.rategain.Reservation")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class ReservationService_ReservationServiceSoapImpl
    implements Reservation
{


    public ReservationService_ReservationServiceSoapImpl() {
    }

    /**
     * 
     * @param otaHotelResNotifRQ
     * @return
     *     returns com.traveliko.ws.platform.rategain.OTAHotelResNotifRS
     */
    public OTAHotelResNotifRS otaHotelResNotifRQ(OTAHotelResNotifRQ otaHotelResNotifRQ) {
        //replace with your impl here
        return null;
    }

}
