
package com.rategain.cgbridge._2011a;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReservationService", targetNamespace = "http://cgbridge.rategain.com/2011A", wsdlLocation = "/DirectConnectReservation.wsdl")
public class ReservationService
    extends Service
{

    private final static URL RESERVATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException RESERVATIONSERVICE_EXCEPTION;
    private final static QName RESERVATIONSERVICE_QNAME = new QName("http://cgbridge.rategain.com/2011A", "ReservationService");

    static {
        RESERVATIONSERVICE_WSDL_LOCATION = com.rategain.cgbridge._2011a.ReservationService.class.getResource("/DirectConnectReservation.wsdl");
        WebServiceException e = null;
        if (RESERVATIONSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/DirectConnectReservation.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        RESERVATIONSERVICE_EXCEPTION = e;
    }

    public ReservationService() {
        super(__getWsdlLocation(), RESERVATIONSERVICE_QNAME);
    }

    public ReservationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RESERVATIONSERVICE_QNAME, features);
    }

    public ReservationService(URL wsdlLocation) {
        super(wsdlLocation, RESERVATIONSERVICE_QNAME);
    }

    public ReservationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RESERVATIONSERVICE_QNAME, features);
    }

    public ReservationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReservationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Reservation
     */
    @WebEndpoint(name = "ReservationServiceSoap")
    public Reservation getReservationServiceSoap() {
        return super.getPort(new QName("http://cgbridge.rategain.com/2011A", "ReservationServiceSoap"), Reservation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Reservation
     */
    @WebEndpoint(name = "ReservationServiceSoap")
    public Reservation getReservationServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://cgbridge.rategain.com/2011A", "ReservationServiceSoap"), Reservation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RESERVATIONSERVICE_EXCEPTION!= null) {
            throw RESERVATIONSERVICE_EXCEPTION;
        }
        return RESERVATIONSERVICE_WSDL_LOCATION;
    }

}
